### ISSUE TITLE
【BUG】Failed to handle relative addresses when copying bytes

### ISSUE THREAD

**Issue by cngege** [SamuelTulach/LightHook#10]
![QQ_1726400900012](https://github.com/user-attachments/assets/dfb09e35-1c3c-4f2c-9f5c-ff874c06ff99)

![QQ_1726400845145](https://github.com/user-attachments/assets/cc844b40-69c6-440f-9523-518e2394d54f)

"Please note the section within the red box. These bytes were copied to the new memory address as is, including the relative address `D5049001`. Since LightHook did not convert this relative address during the copying process, it led to a program crash after hooking."

**Comment by cngege** [comment]
MINHOOK has no such problem

**Comment by SamuelTulach** [comment]
This is just how LightHooks works. It is supposed to be used in scenarios where you know what the hooked function is going to look like. There is no way to fix it, since there is no disassembler, just instruction length is parsed. If there is function with relative addressing used, it will fail. Also I would like to note that you cannot do mid function hooks (the screenshot appears to not show function start), unless you point the hook into a manually crafted assembly that will correctly handle the current state of registers.
